In [8]:
import pandas as pd

In [ ]:
df = pd.concat([pd.read_csv("maestro_vk.csv", index_col=0),
                pd.read_csv("maestro_blog.csv", index_col=0),
                pd.read_csv("maestro_books.csv", index_col=0)])

In [89]:
from razdel import sentenize


def sentify(df):
    df["sentence"] = df.text.apply(lambda y: [x.text for x in sentenize(y)])
    df = df.explode("sentence").reset_index(drop=True).drop("text", axis=1)
    return df

In [120]:
for df_name in [f"maestro_{i}.csv" for i in ["vk", "blog", "books"]]:
    df = pd.read_csv(df_name, index_col=0)
    sentify(df).to_csv(f"sent_{df_name}")

In [2]:
df = pd.concat([pd.read_csv("sent_maestro_vk.csv", index_col=0),
                pd.read_csv("sent_maestro_blog.csv", index_col=0),
                pd.read_csv("sent_maestro_books.csv", index_col=0)])

In [9]:
df = pd.read_csv("sent_combined.csv", index_col=0)
df.head()

url  \
0  https://vk.com/@evgenyponasenkov-kutuzovskii-p...   
1  https://vk.com/@evgenyponasenkov-kutuzovskii-p...   
2  https://vk.com/@evgenyponasenkov-kutuzovskii-p...   
3  https://vk.com/@evgenyponasenkov-kutuzovskii-p...   
4  https://vk.com/@evgenyponasenkov-kutuzovskii-p...   

                                               title        date  \
0  Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24   
1  Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24   
2  Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24   
3  Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24   
4  Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24   

                                            sentence  
0                          Начну, простите, с конца.  
1  Да, митинги 10-го и 24-го декабря – это замеча...  
2  У России был один приближенный к серьезному ша...  
3  Немного снижая пафос, можно было бы вспомнить ...  
4  Собственно на этом я бы и завершил статью, одн...

In [11]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'[^\d\W]+')

In [ ]:
class :
    def __init__(self, v=None):
        self.v = v

Быстрее всего искать что-либо в хешированных структурах, так что в идеале жолжен быть сет, либо хотя бы словрь. Словарь хорош тем, что в него можно сразу затолкать лемму и разбор слова

In [2]:
def preprocess(text):
    global i
    global df2

    lowered = tokenizer.tokenize(text.lower())
    forms = predictor.predict(lowered)
    clear_output()
    tokens = {}
    lemmas = {}
    poss = {}
    for form in forms:
        word = form.word
        lemma = form.normal_form
        pos = form.pos

        if word in tokens:
            tokens[word] += [i]
        else:
            tokens.update({word: [i]})

        if lemma in lemmas:
            lemmas[lemma] += [i]
        else:
            lemmas.update({lemma: [i]})

        if pos in poss:
            poss[pos] += [i]
        else:
            poss.update({pos: [i]})

        df2 = pd.concat([df2, pd.DataFrame({"token": word,
                                            "lemma": lemma,
                                            "pos": pos,
                                            "tag": form.tag
                                           },
                                            index=[i])])

        i += 1

    return {"tokens": tokens, "lemmas": lemmas, "poss": poss}

In [ ]:
del

In [ ]:
# в основном датафрейме храню только список токенов
# по нему будет искаться быстро, если нашёлся, беру номер предложения
# залетаю в токены, беру значение токена, это будет индекс в бд морфологии
# достаю из морфологии всю инфу

In [3]:
from IPython.display import clear_output
from tqdm import tqdm
tqdm.pandas()

In [17]:
i = 98268

In [6]:
i = 360656

In [45]:
pd.read_csv("morph_info.csv")

token     lemma   pos  \
0          начну    начать  VERB   
1       простите  простить  VERB   
2              с         с   ADP   
3          конца     конец  NOUN   
4             да        да  CONJ   
...          ...       ...   ...   
481850         о         о   ADP   
481851    сповах   споваха  NOUN   
481852  эпиграфа   эпиграф  NOUN   
481853        их        он   DET   
481854    смысле     смысл  NOUN   

                                                      tag  
0       Mood=Ind|Number=Sing|Person=1|Tense=Notpast|Ve...  
1       Mood=Imp|Number=Plur|Person=2|VerbForm=Fin|Voi...  
2                                                       _  
3                        Case=Gen|Gender=Masc|Number=Sing  
4                                                       _  
...                                                   ...  
481850                                                  _  
481851                   Case=Loc|Gender=Masc|Number=Plur  
481852                   Case=Gen|Gender=Masc|Number=Sing  
481853                                                  _  
481854                   Case=Loc|Gender=Masc|Number=Sing  

[481855 rows x 4 columns]

In [21]:
del t

In [41]:
morph_info = pd.concat([pd.read_csv(f"morph_info_{i}.csv") for i in range(6)])

In [40]:
parsed_sents = pd.concat([pd.read_csv(f"parsed_{i}.csv") for i in range(6)])

In [43]:
parsed_sents = pd.read_csv("parsed_sents.csv")

In [51]:
df.iloc[:, :-1].to_csv("sents_meta.csv", index=0)

In [53]:
sents_meta = pd.read_csv("sents_meta.csv")
sents_meta

url  \
0      https://vk.com/@evgenyponasenkov-kutuzovskii-p...   
1      https://vk.com/@evgenyponasenkov-kutuzovskii-p...   
2      https://vk.com/@evgenyponasenkov-kutuzovskii-p...   
3      https://vk.com/@evgenyponasenkov-kutuzovskii-p...   
4      https://vk.com/@evgenyponasenkov-kutuzovskii-p...   
...                                                  ...   
26338  https://www.ozon.ru/product/pervaya-nauchnaya-...   
26339  https://www.ozon.ru/product/pervaya-nauchnaya-...   
26340  https://www.ozon.ru/product/pervaya-nauchnaya-...   
26341  https://www.ozon.ru/product/pervaya-nauchnaya-...   
26342  https://www.ozon.ru/product/pervaya-nauchnaya-...   

                                                   title        date  
0      Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24  
1      Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24  
2      Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24  
3      Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24  
4      Кутузовский план Кремля (27. 12. 2011). Запись...  2021-02-24  
...                                                  ...         ...  
26338                           Правда о войне 1812 года        2004  
26339                           Правда о войне 1812 года        2004  
26340                           Правда о войне 1812 года        2004  
26341                           Правда о войне 1812 года        2004  
26342                           Правда о войне 1812 года        2004  

[26343 rows x 3 columns]

In [42]:
parsed_sents.iloc[:, 1:].reset_index(drop=True).to_csv("parsed_sents.csv", index=0)
morph_info.iloc[:, 1:].reset_index(drop=True).to_csv("morph_info.csv", index=0)

In [14]:
df2 = pd.DataFrame({"token":[], "lemma":[] , "pos":[], "tag":[]})

#t = pd.DataFrame(df.sentence.iloc[:10].progress_apply(preprocess).values)
j = 5
t = pd.DataFrame(df.sentence.iloc[j*5000:(j+1)*5000].progress_apply(preprocess).values)
t["lemmas"] = t[0].apply(lambda x: x["lemmas"])
t["tokens"] = t[0].apply(lambda x: x["tokens"])
t["poss"] = t[0].apply(lambda x: x["poss"])
t = t.drop(0, axis=1)
t.to_csv(f"parsed_{j}.csv")
df2.to_csv(f"morph_info_{j}.csv")

100%|██████████████████████████████████████████████████████████████████████████████| 1343/1343 [04:10<00:00,  5.37it/s]


In [9]:
t.iloc[0].poss

NameError: name 't' is not defined

In [322]:
t = pd.concat([df.iloc[:100][["title", "date", "sentence"]], t], axis=1)

In [143]:
word = "знать+VERB"

In [410]:
request = 'NOUN VERB'

In [339]:
"".isalnum()

True

In [336]:
import string

def isEnglish(s):
    return s.isascii()

In [483]:
def search(request, df):
    sub_req = request.split()

    el_chars = {}
    for element in sub_req:
        with_pos = False
        if element[0] == '"':
            element = element[1:-1]
            mode = "lemmas"
        elif element[0].isascii():
            mode = "poss"
        else:
            mode = "tokens"
        if "+" in element:
            with_pos = True
        print(element, mode)
        el_chars.update({element: word_search(element=element,
                                              df=df, mode=mode,
                                              with_pos=with_pos)})

    common_sents = list(reduce(lambda x, y: x & y.keys(), el_chars.values()))
    for sent in common_sents:
        # беру разницу элементов массива, она должна быть равна длине массива -1
        #word_indices = [el_chars[key][sent][0] for key in el_chars]
        listik = []
        for key in el_chars:
            listik.append(el_chars[key][sent])
        grid = np.array(np.meshgrid(*listik)).T.reshape(-1, len(el_chars))
        diffs = np.apply_along_axis(custom_diff, arr=grid, axis=1)
        word_indices = diffs[np.where(diffs == len(el_chars)-1)]
        if len(word_indices) > 0:
            print_out(sent, word_indices, df)

In [308]:
def print_out(sent_indice, word_indice, df):
    row = df.iloc[sent_indice]
    print(row.sentence)
    print(row.title)
    print(row.date)
    print("")

In [396]:
def flatten(l):
    return [item for sublist in l for item in sublist]

In [16]:
from functools import reduce

In [5]:
import numpy as np

In [478]:
grid = np.array(np.meshgrid([3], [0, 2])).T.reshape(-1, 2)
custom_diff = lambda z: reduce(lambda x, y: abs(x - y), z)
diffs = np.apply_along_axis(custom_diff, arr=grid, axis=1)
diffs[np.where(diffs == 1)]

array([1])

In [476]:
diffs

array([3, 2])

In [ ]:
search(request, df=t)

In [407]:
a = np.array([1, 2, 3, 4])
np.abs(np.subtract.outer(a, a))

array([[0, 1, 2, 3],
       [1, 0, 1, 2],
       [2, 1, 0, 1],
       [3, 2, 1, 0]])

In [ ]:
pd.merge(pd.DataFrame(word_search("не", t, mode="tokens")),
         pd.DataFrame(word_search("знать", t, mode="lemmas")))

In [328]:
def word_search(element, df=df, df2=df2, mode="tokens", with_pos=False):

    if with_pos:
        word, pos = element.split("+")
        word_indices = word_search(word, df, df2, mode)
        pos_indices = word_search(pos, df, df2, mode="poss")
        indices = word_indices.keys() & pos_indices.keys()
        morph_indices = []
        for sent in indices:
            morph_indices.append(list(set(word_indices[sent]) & set(pos_indices[sent])))

    else:
        v = np.vectorize(lambda x: element in x)
        indices = np.where(v(df[mode]) == True)[0]

        #for i in indices:
            #print(i)
        row = df.iloc[indices]
        #print(row.lemmas)
        #print(row.sentence)
        #print(row.title)
        #print(row.date)
        morph_indices = row[mode].apply(lambda x: x[element])
        if with_pos:
        #print(row[mode].apply(lambda x: x[word]))  # индексы находятся списками
            morph = df2.iloc[morph_indices.sum()]
            u = np.vectorize(lambda x: x == pos)

            #print(f"""\tnormal form - {morph.lemma.unique()}
            #word - {morph.token.unique()}
            #pos - {morph.pos.unique()}
            #tag - {morph.tag.unique()}""")
            #print("")
        
    return dict(zip(indices, morph_indices))

In [233]:
df3 = pd.concat([
           pd.DataFrame({"url": "test0",
                         "title": "test1",
                         "date": "test2",
                         "sentence": "сегодня тут ужинает высшая знать"}, index=[0]),
    df])

In [330]:
word_search("знать+VERB", t, mode="tokens", with_pos=True)

{87: [2026]}

In [ ]:
word_search("VERB", t, mode="poss", with_pos=False)

In [329]:
word_search("знать+NOUN", t, mode="tokens", with_pos=True)

{87: []}

In [331]:
word_search("знать", t, mode="tokens", with_pos=False)

{87: [2026]}

In [651]:
print(df.iloc[398]["sentence"])

Конечно, не обошлось и без дипломированных лицедеев – актрисы Натальи Селезневой и актера Валерия Баринова.


In [867]:
a, b, c, d = word_search(word, t, mode="lemmas")

9      [281]
87    [2026]
Name: lemmas, dtype: object


In [627]:
%%time
v = np.vectorize(lambda x: word in x)

indices = np.where(v(t["tokens"]) == True)

t.iloc[indices]["tokens"].apply(lambda x: df2.iloc[x[word]].values[0])
#chars = s.iloc[indices]["lemmas"].apply(lambda x: x[word])

CPU times: total: 0 ns
Wall time: 998 µs


0    [начну, начать, VERB, Mood=Ind|Number=Sing|Per...
Name: tokens, dtype: object

In [647]:
j = [0, 1]

for i in j:
    print(df.iloc[i]["sentence"])
    morph = df2.iloc[i]
    print(f"""\tnormal form - {morph.lemma}
        pos - {morph.pos}
        tag - {morph.tag}""")

Начну, простите, с конца.
	normal form - начать
        pos - VERB
        tag - Mood=Ind|Number=Sing|Person=1|Tense=Notpast|VerbForm=Fin|Voice=Act
Да, митинги 10-го и 24-го декабря – это замечательная веха отечественной истории, да, прежде всего, это дыхание весны и романтики (я вообще вижу в них, прежде всего, художественный смысл), но (не хочу оказаться правым) ОНИ вам ничего не отдадут.
	normal form - простить
        pos - VERB
        tag - Mood=Imp|Number=Plur|Person=2|VerbForm=Fin|Voice=Act


In [622]:
t.iloc[indices]["tokens"].apply(lambda x: df2["token"].iloc[x[word]])

84
0  начну

In [464]:
s = pd.concat([df.iloc[:1000].sentence, s], axis=1)

In [465]:
v = np.vectorize(lambda x: (x["pos"], x["tag"]))
v(chars.values)

(array(['VERB', 'VERB', 'VERB', 'VERB', 'VERB', 'VERB', 'VERB', 'VERB',
        'VERB', 'VERB', 'VERB'], dtype='<U4'),
 array(['Mood=Ind|Number=Sing|Person=1|Tense=Notpast|VerbForm=Fin|Voice=Act',
        'Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin|Voice=Act',
        'Mood=Ind|Number=Plur|Person=3|Tense=Notpast|VerbForm=Fin|Voice=Act',
        'Mood=Ind|Number=Sing|Person=1|Tense=Notpast|VerbForm=Fin|Voice=Act',
        'Mood=Ind|Number=Plur|Person=1|Tense=Notpast|VerbForm=Fin|Voice=Act',
        'Mood=Ind|Number=Plur|Tense=Past|VerbForm=Fin|Voice=Act',
        'Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin|Voice=Act',
        'Gender=Fem|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin|Voice=Act',
        'VerbForm=Inf',
        'Mood=Ind|Number=Plur|Tense=Past|VerbForm=Fin|Voice=Act',
        'Mood=Ind|Number=Sing|Person=3|Tense=Notpast|VerbForm=Fin|Voice=Act'],
       dtype='<U66'))

In [ ]:
3 ms - занимает поиск

In [ ]:
# 4 колонки, сначала ищу по датафрейму, это супербыстро с векторайзом, потом в каждой строке ищу индекс один раз, вывожу всю инфу из 4 колонок

In [ ]:
#apply - 188 ms vs vectorize - 15 ms
# подход со словарём уоскрил в 3 раза

In [376]:
indices

(array([0], dtype=int64),)

In [406]:
word = "да"

In [432]:
print(s[["tokens"]].iloc[indices]["tokens"].apply(lambda x: x[word]))
print("!")

1     {'pos': 'CONJ', 'tag': '_'}
12    {'pos': 'CONJ', 'tag': '_'}
22    {'pos': 'CONJ', 'tag': '_'}
30    {'pos': 'CONJ', 'tag': '_'}
47    {'pos': 'CONJ', 'tag': '_'}
Name: tokens, dtype: object
!


In [386]:
# думаю, что так лучше всего, тогда можно по индексу сразу найти предложение, его вывести
# в соотв колонке сразу обратиться по ключу, достать морфоприколы + лемму
# но нужно сделать что-то подобное с другим словарём тоже

# или сделать другую бд, но искать-же всё равно надо по хэшу, а где мне его ещё достать
# обязательно должно что-то на что-то ссылаться
# наверное надо всё-таки хранить лемму в токене тоже и наоборот
# токены надо хранить в сете, иначе я их буду долго искать

# судя по всему список позов тоже нужно хранить, но там нужен только сет,
# чтобы достать форму+поз я посмотрю по словарю


А если всё-таки всё разбить? Искать слово. Допустим, нашёл, вернул индекс, написал предложение + всё, что просят. Вроде так максимально просто. Если поиск в пандасе такой же быстрый как в словаре

In [12]:
from rnnmorph.predictor import RNNMorphPredictor

predictor = RNNMorphPredictor(language="ru")

In [204]:
forms = predictor.predict(["мама", "мыла", "раму"])
print(forms[0].pos)
print(forms[0].tag)
print(forms[0].normal_form)
forms[0].word

1/1 [==============================] - 0s 20ms/step
NOUN
Case=Nom|Gender=Fem|Number=Sing
мама


'мама'